name: reddit_clone
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bloc_use_case_generator: ^1.0.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_gen_runner: ^5.0.2
  flutter_svg: ^1.1.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
  colors:
    inputs:
      - assets/color/colors.xml
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
