name: reddit_clone
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.3.2
  flutter_svg: ^1.1.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^2.6.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
    - assets/image/
    - assets/icon/
